// Generated by CoffeeScript 1.7.1
(function() {
  /**
   @const
   @type {boolean}
*/
var WEB = true;
;
  var exports;

  exports = window['sharejs'];

}).call(this);

//# sourceMappingURL=web-prelude.map
