// Generated by CoffeeScript 1.7.1
(function() {
  var DeleteMismatchError, Errors, NotFoundError, OpRangeNotAvailableError, ProjectStateChangedError;

  NotFoundError = function(message) {
    var error;
    error = new Error(message);
    error.name = "NotFoundError";
    error.__proto__ = NotFoundError.prototype;
    return error;
  };

  NotFoundError.prototype.__proto__ = Error.prototype;

  OpRangeNotAvailableError = function(message) {
    var error;
    error = new Error(message);
    error.name = "OpRangeNotAvailableError";
    error.__proto__ = OpRangeNotAvailableError.prototype;
    return error;
  };

  OpRangeNotAvailableError.prototype.__proto__ = Error.prototype;

  ProjectStateChangedError = function(message) {
    var error;
    error = new Error(message);
    error.name = "ProjectStateChangedError";
    error.__proto__ = ProjectStateChangedError.prototype;
    return error;
  };

  ProjectStateChangedError.prototype.__proto__ = Error.prototype;

  DeleteMismatchError = function(message) {
    var error;
    error = new Error(message);
    error.name = "DeleteMismatchError";
    error.__proto__ = DeleteMismatchError.prototype;
    return error;
  };

  DeleteMismatchError.prototype.__proto__ = Error.prototype;

  module.exports = Errors = {
    NotFoundError: NotFoundError,
    OpRangeNotAvailableError: OpRangeNotAvailableError,
    ProjectStateChangedError: ProjectStateChangedError,
    DeleteMismatchError: DeleteMismatchError
  };

}).call(this);

//# sourceMappingURL=Errors.map
