// Generated by CoffeeScript 1.7.1
(function() {
  var HistoryRedisManager, Keys, Settings, logger, rclient;

  Settings = require('settings-sharelatex');

  rclient = require("redis-sharelatex").createClient(Settings.redis.history);

  Keys = Settings.redis.history.key_schema;

  logger = require('logger-sharelatex');

  module.exports = HistoryRedisManager = {
    recordDocHasHistoryOps: function(project_id, doc_id, ops, callback) {
      if (ops == null) {
        ops = [];
      }
      if (callback == null) {
        callback = function(error) {};
      }
      if (ops.length === 0) {
        return callback(new Error("cannot push no ops"));
      }
      logger.log({
        project_id: project_id,
        doc_id: doc_id
      }, "marking doc in project for history ops");
      return rclient.sadd(Keys.docsWithHistoryOps({
        project_id: project_id
      }), doc_id, function(error) {
        if (error != null) {
          return callback(error);
        }
        return callback();
      });
    }
  };

}).call(this);

//# sourceMappingURL=HistoryRedisManager.map
