// Generated by CoffeeScript 1.7.1
(function() {
  var showLength, showUpdateLength, _;

  _ = require('lodash');

  showLength = function(thing) {
    if (thing != null ? thing.length : void 0) {
      return thing.length;
    } else {
      return thing;
    }
  };

  showUpdateLength = function(update) {
    var copy;
    if ((update != null ? update.op : void 0) instanceof Array) {
      copy = _.cloneDeep(update);
      copy.op.forEach(function(element, index) {
        var _ref, _ref1, _ref2;
        if ((element != null ? (_ref = element.i) != null ? _ref.length : void 0 : void 0) != null) {
          copy.op[index].i = element.i.length;
        }
        if ((element != null ? (_ref1 = element.d) != null ? _ref1.length : void 0 : void 0) != null) {
          copy.op[index].d = element.d.length;
        }
        if ((element != null ? (_ref2 = element.c) != null ? _ref2.length : void 0 : void 0) != null) {
          return copy.op[index].c = element.c.length;
        }
      });
      return copy;
    } else {
      return update;
    }
  };

  module.exports = {
    lines: showLength,
    oldLines: showLength,
    newLines: showLength,
    docLines: showLength,
    newDocLines: showLength,
    ranges: showLength,
    update: showUpdateLength
  };

}).call(this);

//# sourceMappingURL=LoggerSerializers.map
