// Generated by CoffeeScript 1.7.1
(function() {
  var Settings, db, mongojs;

  Settings = require("settings-sharelatex");

  mongojs = require("mongojs");

  db = mongojs(Settings.mongo.url, ["docSnapshots"]);

  module.exports = {
    db: db,
    ObjectId: mongojs.ObjectId,
    healthCheck: function(callback) {
      return db.runCommand({
        ping: 1
      }, function(err, res) {
        if (err != null) {
          return callback(err);
        }
        if (!res.ok) {
          return callback(new Error("failed mongo ping"));
        }
        return callback();
      });
    }
  };

}).call(this);

//# sourceMappingURL=mongojs.map
